In [1]:
import matplotlib.pyplot as plt
import sympy as sp 
import numpy as np
from sympy.abc import x

In [2]:

pol = [1, 0 , 5, 7, 8, 3]
k = np.polyval(pol,-2)
print(k)
print(f"Значение полинома в точке x = -2 равно {np.polyval(pol, -2)}.")

-57
Значение полинома в точке x = -2 равно -57.


## Упражнение 1

In [3]:
pol = [1,0,0,3.2,0,3,0,3]
arr = np.array([-1,4,2.2,np.pi])
for i in arr:
    print(np.polyval(pol,i))

8.2
17254.2
341.91770880000024
3364.6111322888664


In [4]:
pol = [1, 0, 5, 7, 8, 3]
print(f"Корни полинома равны:")
for root in np.roots(pol):
    print(f"{root : .3f}")

Корни полинома равны:
 0.759+2.283j
 0.759-2.283j
-0.500+0.866j
-0.500-0.866j
-0.518+0.000j


In [5]:
np.poly([0.7592 + 2.2827j, 0.7592 - 2.2827j, -0.5000 + 0.8660j, -0.5000 -
0.8660j, -0.5184])

array([1.        , 0.        , 4.99992137, 7.00004405, 7.99978005,
       2.99990268])

## Упражнение 2

In [6]:
pol1 = [2,0,0,-3,0,0,7,0,-2]
a = np.roots(pol1)
print(a)
print(np.poly(a))

[-0.95858847+0.79517756j -0.95858847-0.79517756j -0.15141803+1.25356873j
 -0.15141803-1.25356873j  1.09270397+0.46782683j  1.09270397-0.46782683j
 -0.51793877+0.j          0.55254384+0.j        ]
[ 1.00000000e+00  1.77635684e-15 -1.88737914e-15 -1.50000000e+00
 -8.54871729e-15 -4.32986980e-15  3.50000000e+00  2.66453526e-15
 -1.00000000e+00]


## Упражнение 3 

In [7]:
pol1 = [1,2,0,0,-3,0,4]
pol2 = [1,0,-3,1]
a = np.roots(pol1)
b = np.roots(pol2)
c,d = np.polydiv(a,b)
print(c,d,sep = '\n')

[1.17241463-0.j         1.12303929-0.69170274j 1.29944161+0.1278215j
 1.79893266-0.02362046j]
[-2.29132666+0.41089614j  0.29132666-0.41089614j]


## Упражнение 4

In [8]:
def plusik(pol1,pol2):
    pol1 = np.array(pol1)
    pol2 = np.array(pol2)

    a = len(pol1)
    b = len(pol2)
    d = abs(a-b)
    t = 0
    if a>b:
        z = np.zeros(d)
        t = np.concatenate((z,pol2),axis =0) + pol1
    else:
        z = np.zeros(d)
        t = np.concatenate((z,pol),axis =0) + pol2
    return t

In [9]:
pol1 = [1,2,0,0,-3,0,4]
pol2 = [1,0,-3,1]
print(plusik(pol1,pol2))

[ 1.  2.  0.  1. -3. -3.  5.]


## Упражнение 5

In [24]:
pol1 = np.array([1,-1,0,-3,0,-2])
pol2 = np.array([1,0,0,0,0,-3,1])
su = np.polyder(np.convolve(pol1,pol2))
ch = np.polyder(np.polydiv(pol1,pol2))
gg = np.polyder(pol1)
gg1 = np.polyder(pol2)
print(pol1, pol2, su, ch, gg, gg1, sep = '\n')

[ 1 -1  0 -3  0 -2]
[ 1  0  0  0  0 -3  1]
[ 11 -10   0 -24   0 -30  20  -4  27  -6   6]
[array([0.])]
[ 5 -4  0 -6  0]
[ 6  0  0  0  0 -3]


## Упражнение 6

In [26]:
def aa(p):
    return np.polyder(p,5)

In [27]:
vec = (1,0,0,-1,0,0,0,0,3,0,-2)
t = aa(vec)
print(np.polyval(t,0.2))
print(t)    

-91.1232
[30240     0     0 -2520     0     0]


## Упражнение 7

In [41]:
import math
def Teilor(poly,point,n):
    b = []
    ans = 0
    for i in range(n):
        pr = np.polyder(poly,i)
        k = np.polyval(pr,point)/math.factorial(i)
        b.append(k)
    return b[::-1]



In [42]:
p = [1,0,2,0,0,-3,-2]
step1 = [1,-1]
step2 = [1,2]
print(Teilor(p,1,6))
print(Teilor(p,-2,6))


[6.0, 17.0, 28.0, 27.0, 11.0, -2.0]
[-12.0, 62.0, -176.0, 288.0, -259.0, 100.0]


# C1

In [15]:
pol1 = [1,0,0,0,0,0,-1]
a = np.roots(pol1)
print(a)
print(np.poly(a))

[-1. +0.j        -0.5+0.8660254j -0.5-0.8660254j  0.5+0.8660254j
  0.5-0.8660254j  1. +0.j       ]
[ 1.00000000e+00 -2.10942375e-15  7.77156117e-16 -1.55431223e-15
  6.66133815e-16 -5.55111512e-16 -1.00000000e+00]


# C2

In [16]:
pol1 = np.array([1,1,1])
pol2 = np.array([1,-1])
cel,os = np.polydiv(pol1,pol2)
pro = np.convolve(pol1,pol2)
plus = plusik(pol1,pol2)
print(pol1, pol2,cel,os, pro, plus, sep = '\n')

[1 1 1]
[ 1 -1]
[1. 2.]
[3.]
[ 1  0  0 -1]
[1. 2. 0.]


# C3

In [17]:
p = np.array([1,-2,0,1])
step = np.array([1,-2])

g = Teilor(p,2,3)

print(g)

[1.0, 4.0, 4.0]
